### PR TITLE
don't echo credentials on upload/download

### PR DESCRIPTION
**Pull request by mightyguava**

### CODE REVIEW

**Review by gregwebs — APPROVED** [review]
Thank you! The AWS charts already stopped using this file. @tennix make sure to include this in the updated chart release.

**Comment by mightyguava** [comment]
> The AWS charts already stopped using this file.

I still see the credentials echo'ed by this file using the charts on master. What are the AWS charts you refer to?

**Comment by gregwebs** [comment]
sorry, tidb-backup AWS is still using this. tidb-backup GCP is no longer using this.

@tennix you have some changes on your fork of tidb-operator that have not been sent as a PR to master yet. Once sent, this script would only be used for ceph, but not for aws.

**Comment by tennix** [comment]
> sorry, tidb-backup AWS is still using this. tidb-backup GCP is no longer using this.
> 
> @tennix you have some changes on your fork of tidb-operator that have not been sent as a PR to master yet. Once sent, this script would only be used for ceph, but not for aws.

Yes, I think it's better to do this in tidb-operator repo similar to the gcp part: https://github.com/pingcap/tidb-operator/blob/master/charts/tidb-backup/templates/scripts/_start_backup.sh.tpl#L53-L72

What we need for the backup/restore image is some utils binaries: mysql/mydumper/pigz/rclone.

And sorry, I forgot to push my changes to upstream https://github.com/tennix/tidb-operator/blob/backup-s3/charts/tidb-backup/templates/scripts/_start_backup.sh.tpl#L82-L94

**Comment by tennix** [comment]
On public cloud, we can actually assign an IAM profile to a Pod which can avoid explicitly creating a credential secret. In this case, we can specify rclone's config `env_auth = true`, the rclone will get the credentials with web identity role, see here https://github.com/rclone/rclone/pull/3837

**Review by aylei — APPROVED** [review]
LGTM

**Comment by mightyguava** [comment]
> On public cloud, we can actually assign an IAM profile to a Pod which can avoid explicitly creating a credential secret.

That would be lovely. Unfortunately our cluster doesn't have EKS IAM roles enabled yet and it might be a while before we get there

**Comment by mightyguava** [comment]
Can this be merged? I don't have a merge button

**Pull request merged**
